steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$(params.IMAGE)'
      - '.'

images:
  - '$(params.IMAGE)'

substitutions:
  _IMAGE: "us-central1-docker.pkg.dev/iam-project-498112/cloud-run-jobs/employee-data-copy-job:latest"
